export const SETUSRINFO = "SETUSRINFO";

export const SETSIGNINSTATE = "SETSIGNINSTATE";

export const ADDGROUP = "ADDGROUP";
export const EDITLISTNAME = "EDITLISTNAME";
export const EDITEDLISTNAME = "EDITEDLISTNAME";
export const CHANGELISTNAME = "CHANGELISTNAME";
export const EDITTASKNAME = "EDITTASKNAME";
export const EDITEDTASKNAME = "EDITEDTASKNAME";
export const EDITTASKGROUPNAME = "EDITTASKGROUPNAME";
export const EDITEDTASKGROUPNAME = "EDITEDTASKGROUPNAME";
export const SHOWTASKS = "SHOWTASKS";
export const SHOWLISTS = "SHOWLISTS";
export const CHANGESTATUS = "CHANGESTATUS";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const FETCH_ALL_TASKLIST = "FETCH_ALL_TASKLIST";
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const MOVE_TASK_FROM = "MOVE_TASK_FROM";
export const MOVE_TO_TASK = "MOVE_TO_TASK";
export const MOVE_TASK_DONE = "MOVE_TASK_DONE";
